# 后端配置：告诉CMS连接到您的GitHub仓库
backend:
  name: git-gateway
  branch: main # 您的主分支名

# 媒体文件配置 (我们暂时用不到，但最好写上)
media_folder: "static/images"
public_folder: "/images"

# 集合配置：定义您可以管理的内容类型
collections:
  # 这是我们对 examData 数组的管理配置
  - name: "exams" # 集合的内部名称
    label: "考试信息" # 在后台界面上显示的名称
    folder: "_data" # 重要：CMS会将数据保存到这个新文件夹中，而不是直接修改data.js
    create: true # 允许创建新条目
    slug: "{{name}}" # 文件名将基于考试名称生成
    fields: # 定义每个条目的字段
      - { label: "资格名称", name: "name", widget: "string" }
      - { label: "学科门类", name: "discipline", widget: "select", options: ["哲学", "经济学", "法学", "教育学", "文学", "历史学", "理学", "工学", "农学", "医学", "管理学", "艺术学", "其他"] }
      - { label: "类别", name: "category", widget: "select", options: ["准入类", "水平评价类", "其他"] }
      - { label: "官方链接", name: "url", widget: "string" }
      - { label: "备注", name: "notes", widget: "markdown" } # 使用Markdown编辑器，功能类似富文本